services:
  eureka-server:
    build:
      context: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - blog-network

  api-gateway:
    build:
      context: ./Gateway
    container_name: api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - eureka-server
    networks:
      - blog-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka


  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - blog-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka

networks:
  blog-network:
    driver: bridge
