apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: docker.io/flaren/ms-02:1.0
          ports:
            - containerPort: 8761
      imagePullSecrets:
        - name: myregistry-secret
